CONF_THRESH = 0.3
MODEL_IMAGE_SIZE = 416
DETECTION_FRAME_SKIP = 2
ACTIVE_LOOP_DELAY = 0.08
IDLE_LOOP_DELAY = 0.3
UI_REFRESH_SECONDS = 0.4

MIN_GREEN = 5
MAX_GREEN = 30
YELLOW_TIME = 2.0

ALLOWED_CLASSES = {
    2: "car",
    3: "motorcycle",
    5: "bus",
    7: "truck"
}
